groups:
- name: container_alerts
  rules:
  - alert: Reinicio_Contenedor
    # Detecta si un contenedor ha sido reiniciado en los últimos 15 minutos
    expr: delta(container_start_time_seconds{name!=""}[15m]) > 0
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "Se reinicio el contenedor  ({{ $labels.name }})"
      description: "Container {{ $labels.name }} has restarted in the last 15 minutes"
      
  - alert: Alto_Uso_Memoria_Contenedor
    # Detecta si el uso de memoria de un contenedor supera el 80% de su límite
    expr: (container_memory_usage_bytes{name!=""} / container_spec_memory_limit_bytes{name!=""} * 100) > 80
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "Alto uso de la memoria del contenedor ({{ $labels.name }})"
      description: "Container {{ $labels.name }} memory usage is {{ $value }}%"
      
  - alert: ContainerCPUThrottling
    # Detecta si un contenedor está siendo limitado en el uso de CPU
    # Esto ocurre cuando el contenedor intenta usar más CPU de la que se le ha asign
    expr: rate(container_cpu_cfs_throttled_periods_total{name!=""}[5m]) / rate(container_cpu_cfs_periods_total{name!=""}[5m]) > 0.25
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "Limitacion de la CPU del contened ({{ $labels.name }})"
      description: "Container {{ $labels.name }} is being throttled {{ $value | humanizePercentage }}"